"use client";

import { FormEvent, Suspense, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Footer, SiteNav } from "../../components/SiteChrome";
import { useLocale } from "../../components/Locale";

const content = {
  en: {
    eyebrow: "WHOLESALE · OEM / ODM · HOTEL PROJECTS", hero: <>Let’s start with<br />the <i>right questions.</i></>, heroText: "Send your product reference, quantity, target market or project requirements. We’ll turn it into a practical next step.",
    routes: [["01", "Wholesale product inquiry", "Catalogs, prices, MOQ, finishes and packaging information for existing models."], ["02", "Custom lighting development", "Drawings, a sample or a reference image for a new or modified fixture."], ["03", "Hotel & commercial project", "Coordinated decorative lighting for hospitality and commercial interiors."], ["04", "Distributor support", "Marketing images, formal catalogs and long-term collection planning."]],
    formEye: "GET A MORE ACCURATE QUOTATION", formTitle: <>Share the details<br />that affect <i>production.</i></>, formText: "A professional quotation needs more than an image. Include the information already available and our team can identify the rest.", selected: "Selected models:", name: "Your name", email: "Work email", company: "Company / project", message: "Products, quantity, dimensions, finish, destination market or project schedule", consent: "I agree that the submitted information may be used to respond to this business inquiry.", send: "Send inquiry ↗", success: "Inquiry sent. It is now visible in the demo admin portal.",
    processEye: "WHAT HAPPENS NEXT", processTitle: "A clear path from inquiry to production.", steps: [["01", "Requirement review"], ["02", "Clarification & quotation"], ["03", "Sample or specification confirmation"], ["04", "Production & shipment support"]], faqEye: "FREQUENTLY ASKED QUESTIONS", faqTitle: <>Before you send<br /><i>your requirement.</i></>, faqs: [["What should I send for a quotation?", "A product link or reference, quantity, finish, target market, electrical requirements and packing expectations give us the best starting point."], ["Do you work with individual retail orders?", "This demonstration mirrors a B2B workflow for importers, distributors, contractors, designers and project buyers."], ["How quickly is an inquiry reviewed?", "A basic inquiry can be reviewed within one business day. Custom or technical specifications may need further clarification."], ["Can a series be customized?", "Yes. Size, structure, finish, glass, packaging and electrical specification can be reviewed according to the project brief."]],
  },
  zh: {
    eyebrow: "批发 · OEM / ODM · 酒店项目", hero: <>从正确的问题<br /><i>开始。</i></>, heroText: "告诉我们产品参考、数量、目标市场或项目需求，我们会协助您确定下一步。",
    routes: [["01", "现有产品询盘", "获取现有型号的目录、价格、起订量、表面工艺与包装信息。"], ["02", "定制灯具开发", "提供图纸、样品或参考图片，用于开发新的或改良的灯具。"], ["03", "酒店与商业项目", "为酒店和商业空间协调装饰灯具的整体配置。"], ["04", "经销商支持", "提供营销图片、正式目录和长期的产品系列规划支持。"]],
    formEye: "获得更准确的报价", formTitle: <>分享影响<br /><i>生产的细节。</i></>, formText: "一份专业报价不仅需要图片。请填写已有信息，我们会协助梳理其余要求。", selected: "已选型号：", name: "您的姓名", email: "工作邮箱", company: "公司 / 项目", message: "型号、数量、尺寸、表面工艺、目标市场或项目进度", consent: "我同意将提交的信息用于回复此商业询盘。", send: "发送询盘 ↗", success: "询盘已发送，现可在演示后台中查看。",
    processEye: "后续流程", processTitle: "从询盘到生产的清晰路径。", steps: [["01", "需求评审"], ["02", "澄清与报价"], ["03", "样品或规格确认"], ["04", "生产与发货支持"]], faqEye: "常见问题", faqTitle: <>发送需求前<br /><i>先了解这些。</i></>, faqs: [["报价时应提供哪些信息？", "产品链接或参考图、数量、表面工艺、目标市场、电气要求和包装要求，能帮助我们更准确地评估。"], ["是否接受个人零售订单？", "此演示站模拟面向进口商、经销商、承包商、设计师和项目采购方的 B2B 工作流程。"], ["询盘多久会被处理？", "基础询盘通常可在一个工作日内查看；定制或技术规格可能需要进一步确认。"], ["产品系列可以定制吗？", "可以。尺寸、结构、表面工艺、玻璃、包装和电气规格都可按项目简报评估。"]],
  },
} as const;

function ContactContent() {
  const [done, setDone] = useState(false); const [open, setOpen] = useState<number | null>(null); const { locale } = useLocale(); const t = content[locale];
  const searchParams = useSearchParams(); const selectedModels = searchParams.get("models") || searchParams.get("model") || "";
  const initialMessage = selectedModels ? (locale === "zh" ? `我想咨询以下型号：${selectedModels}\n\n数量 / 项目需求：` : `I would like a quotation for: ${selectedModels}\n\nQuantity / project details: `) : "";
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const response = await fetch("/api/inquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); if (response.ok) { setDone(true); form.reset(); } }
  return <main className="contact-page"><SiteNav /><section className="contact-hero"><span className="eyebrow">{t.eyebrow}</span><h1>{t.hero}</h1><p>{t.heroText}</p></section><section className="contact-routes">{t.routes.map(([number, title, description]) => <article key={number}><b>{number}</b><h2>{title}</h2><p>{description}</p></article>)}</section><section className="contact-form"><div><span className="eyebrow">{t.formEye}</span><h2>{t.formTitle}</h2><p>{t.formText}</p></div><form onSubmit={submit}>{selectedModels && <p className="selected-models">{t.selected} <b>{selectedModels}</b></p>}<input required name="name" placeholder={t.name} /><input required type="email" name="email" placeholder={t.email} /><input name="company" placeholder={t.company} /><textarea required name="message" defaultValue={initialMessage} placeholder={t.message} /><label className="consent"><input required type="checkbox" /> {t.consent}</label><button className="gold">{t.send}</button>{done && <p className="form-success">{t.success}</p>}</form></section><section className="process"><span className="eyebrow">{t.processEye}</span><h2>{t.processTitle}</h2><div>{t.steps.map(([number, title]) => <article key={number}><b>{number}</b><h3>{title}</h3></article>)}</div></section><section className="faq-block"><span className="eyebrow">{t.faqEye}</span><h2>{t.faqTitle}</h2>{t.faqs.map(([question, answer], index) => <article className={open === index ? "expanded" : ""} key={question}><button onClick={() => setOpen(open === index ? null : index)}><b>{String(index + 1).padStart(2, "0")}</b>{question}<span>{open === index ? "−" : "+"}</span></button>{open === index && <p>{answer}</p>}</article>)}</section><Footer /></main>;
}

export default function Contact() { return <Suspense fallback={<main className="contact-page"><SiteNav /><section className="contact-hero"><span className="eyebrow">WHOLESALE · OEM / ODM · HOTEL PROJECTS</span><h1>Let’s start with<br />the <i>right questions.</i></h1></section></main>}><ContactContent /></Suspense>; }
