"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { AdminDashboard } from "../../components/AdminCommerce";
import type { HeroSlide, SiteSettings } from "../../lib/settings";

type Product = { id: string; name: string; model: string; category: string; image: string; status: string; price: string; description: string };
type Inquiry = { id: string; name: string; email: string; company?: string; message: string; status: string; createdAt: string };
type Category = { id: string; name: string; nameZh?: string; slug: string; description: string; published: boolean };
type Tab = "overview" | "homepage" | "products" | "categories" | "inquiries" | "media" | "seo" | "settings";
const tabs: [Tab, string, string][] = [["overview", "概览", "◫"], ["homepage", "首页轮播", "◉"], ["products", "产品管理", "◇"], ["categories", "分类管理", "▤"], ["inquiries", "询盘管理", "◌"], ["media", "媒体库", "▧"], ["seo", "SEO 与页面", "⌘"], ["settings", "网站设置", "⚙"]];

export default function Admin() {
  const [tab, setTab] = useState<Tab>("overview"); const [products, setProducts] = useState<Product[]>([]); const [inquiries, setInquiries] = useState<Inquiry[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [settings, setSettings] = useState<SiteSettings>({}); const [notice, setNotice] = useState("");
  const load = async () => { const [productsData, inquiriesData, categoriesData, settingsData] = await Promise.all([fetch("/api/products").then((response) => response.json()), fetch("/api/inquiries").then((response) => response.json()), fetch("/api/categories").then((response) => response.json()), fetch("/api/settings").then((response) => response.json())]); setProducts(productsData); setInquiries(inquiriesData); setCategories(categoriesData); setSettings(settingsData); };
  useEffect(() => { void load(); }, []);
  async function updateProduct(product: Product, status: string) { await fetch("/api/products", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...product, status }) }); setNotice("产品状态已更新。"); void load(); }
  async function updateInquiry(inquiry: Inquiry, status: string) { await fetch("/api/inquiries", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...inquiry, status }) }); void load(); }
  async function addCategory(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const item = Object.fromEntries(new FormData(form)); const response = await fetch("/api/categories", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...item, published: true }) }); if (response.ok) { form.reset(); setNotice("分类已创建。"); void load(); } else setNotice("分类创建失败，请重试。"); }
  async function saveSettings(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); if (response.ok) { setSettings(await response.json()); setNotice("设置已保存。"); } else setNotice("设置保存失败，请重试。"); }
  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); window.location.href = "/login"; }
  return <main className="cms"><aside className="cms-side"><a className="brand" href="/"><i /> LUMENHAUS<small>后台工作台</small></a><span>网站管理</span><a className="cms-commerce-link" href="/admin/operations">订单、配送与演示业务 →</a>{tabs.map(([id, label, icon]) => <button onClick={() => setTab(id)} className={tab === id ? "active" : ""} key={id}><i>{icon}</i>{label}{id === "inquiries" && inquiries.filter((item) => item.status === "New").length ? <b>{inquiries.filter((item) => item.status === "New").length}</b> : null}</button>)}<div className="cms-profile"><div>LH</div><p>演示管理员<small>全部权限</small></p></div><button className="cms-logout" onClick={() => void logout()}>退出登录</button></aside><section className="cms-content"><header><div><span className="eyebrow">内容管理系统</span><h1>{tabs.find((item) => item[0] === tab)?.[1]}</h1></div><a href="/" className="cms-preview">预览网站 ↗</a></header>{tab === "overview" && <AdminDashboard />}{tab === "homepage" && <HeroCarouselManager settings={settings} setSettings={setSettings} save={saveSettings} />}{tab === "products" && <Products products={products} update={updateProduct} />}{tab === "categories" && <Categories categories={categories} add={addCategory} />}{tab === "inquiries" && <Inquiries inquiries={inquiries} update={updateInquiry} />}{tab === "media" && <Media products={products} />}{tab === "seo" && <Seo settings={settings} setSettings={setSettings} save={saveSettings} />}{tab === "settings" && <SettingsPanel settings={settings} setSettings={setSettings} save={saveSettings} />}</section>{notice && <div className="toast">{notice}<button onClick={() => setNotice("")}>×</button></div>}</main>;
}

function Overview({ products, inquiries, categories }: { products: Product[]; inquiries: Inquiry[]; categories: Category[] }) { return <><div className="cms-metrics"><Metric n={String(products.length)} t="产品记录" /><Metric n={String(products.filter((item) => item.status === "Published").length)} t="已发布产品" /><Metric n={String(inquiries.filter((item) => item.status === "New").length)} t="新询盘" /><Metric n={String(categories.filter((item) => item.published).length)} t="已启用分类" /></div><div className="cms-two"><div className="cms-card"><div className="card-title"><h2>最近询盘</h2><small>实时数据</small></div>{inquiries.slice(0, 5).map((item) => <div className="cms-row" key={item.id}><div className="cms-avatar">{item.name[0]}</div><div><b>{item.name}</b><small>{item.company || item.email}</small></div><em className={item.status.toLowerCase()}>{item.status === "New" ? "新询盘" : item.status === "Contacted" ? "已联系" : item.status === "Quoted" ? "已报价" : "已关闭"}</em></div>)}</div><div className="cms-card"><div className="card-title"><h2>发布检查清单</h2></div><ul className="checklist"><li className="complete">产品目录已填充</li><li className="complete">英文站点文案</li><li className="complete">中文内容字段</li><li className="complete">首页三张轮播图已配置</li><li>连接生产环境邮件投递</li></ul></div></div></>; }
function Metric({ n, t }: { n: string; t: string }) { return <article><b>{n}</b><span>{t}</span></article>; }

function HeroCarouselManager({ settings, setSettings, save }: { settings: SiteSettings; setSettings: (settings: SiteSettings) => void; save: (event: FormEvent) => Promise<void> }) {
  const slides = settings.heroSlides || []; const [uploading, setUploading] = useState<number | null>(null);
  const updateSlide = (index: number, field: keyof HeroSlide, value: string | boolean) => setSettings({ ...settings, heroSlides: slides.map((slide, slideIndex) => slideIndex === index ? { ...slide, [field]: value } : slide) });
  async function uploadImage(index: number, event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setUploading(index); const form = new FormData(); form.set("file", file); const response = await fetch("/api/media", { method: "POST", body: form }); const result = await response.json(); if (response.ok) updateSlide(index, "image", result.url); setUploading(null); event.target.value = ""; }
  return <form className="hero-manager" onSubmit={save}><div className="hero-manager-head"><div><span className="eyebrow">首页 / 3 张轮播</span><h2>首屏轮播图</h2><p>每个首屏位都可以独立替换图片、中英文文案、按钮与跳转链接。发布后首页会自动读取最新设置。</p></div><button className="cms-gold">保存全部轮播</button></div>{slides.map((slide, index) => <section className="hero-slide-editor" key={slide.id}><div className="hero-slide-preview" style={{ backgroundImage: `linear-gradient(90deg, #17130ec4, #17130e30), url("${slide.image}")` }}><span>轮播图 {String(index + 1).padStart(2, "0")}</span><b>{slide.titleZh || slide.title}</b></div><div className="hero-slide-fields"><div className="hero-slide-top"><b>轮播图 {index + 1}</b><label className="publish-switch"><input type="checkbox" checked={slide.published} onChange={(event) => updateSlide(index, "published", event.target.checked)} /> 发布</label></div><label>首屏图片<input value={slide.image} onChange={(event) => updateSlide(index, "image", event.target.value)} /></label><label className="hero-upload"><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={(event) => void uploadImage(index, event)} disabled={uploading === index} /><span>{uploading === index ? "上传中…" : "上传替换图片"}</span></label><div className="hero-field-grid"><label>中文眉题<input value={slide.eyebrowZh} onChange={(event) => updateSlide(index, "eyebrowZh", event.target.value)} /></label><label>英文眉题<input value={slide.eyebrow} onChange={(event) => updateSlide(index, "eyebrow", event.target.value)} /></label></div><div className="hero-field-grid"><label>中文标题<textarea value={slide.titleZh} onChange={(event) => updateSlide(index, "titleZh", event.target.value)} /></label><label>英文标题<textarea value={slide.title} onChange={(event) => updateSlide(index, "title", event.target.value)} /></label></div><div className="hero-field-grid"><label>中文说明<textarea value={slide.descriptionZh} onChange={(event) => updateSlide(index, "descriptionZh", event.target.value)} /></label><label>英文说明<textarea value={slide.description} onChange={(event) => updateSlide(index, "description", event.target.value)} /></label></div><div className="hero-field-grid"><label>中文主按钮<input value={slide.primaryLabelZh} onChange={(event) => updateSlide(index, "primaryLabelZh", event.target.value)} /></label><label>英文主按钮<input value={slide.primaryLabel} onChange={(event) => updateSlide(index, "primaryLabel", event.target.value)} /></label><label>主按钮链接<input value={slide.primaryHref} onChange={(event) => updateSlide(index, "primaryHref", event.target.value)} /></label><label>中文次按钮<input value={slide.secondaryLabelZh} onChange={(event) => updateSlide(index, "secondaryLabelZh", event.target.value)} /></label><label>英文次按钮<input value={slide.secondaryLabel} onChange={(event) => updateSlide(index, "secondaryLabel", event.target.value)} /></label><label>次按钮链接<input value={slide.secondaryHref} onChange={(event) => updateSlide(index, "secondaryHref", event.target.value)} /></label></div></div></section>)}</form>;
}

function Products({ products, update }: { products: Product[]; update: (product: Product, status: string) => Promise<void> }) { return <div className="cms-card"><div className="card-title"><h2>产品目录</h2><a className="cms-gold" href="/admin/products">+ 新建产品</a></div><p className="cms-help">使用完整产品编辑器添加、翻译、发布或删除产品目录记录。</p><div className="cms-table">{products.map((product) => <article key={product.id}><img src={product.image} alt="" /><div><b>{product.name}</b><small>{product.model} · {product.category}</small></div><span>{product.price}</span><select value={product.status} onChange={(event) => void update(product, event.target.value)}><option value="Draft">草稿</option><option value="Published">已发布</option></select><a href={`/product/${product.id}`}>查看 ↗</a></article>)}</div></div>; }
function Categories({ categories, add }: { categories: Category[]; add: (event: FormEvent<HTMLFormElement>) => Promise<void> }) { return <div className="cms-two"><div className="cms-card"><div className="card-title"><h2>产品分类</h2><small>{categories.length} 条记录</small></div>{categories.map((category) => <div className="cms-row" key={category.id}><div className="cms-icon">▤</div><div><b>{category.name} <small>· {category.nameZh}</small></b><small>/{category.slug}</small></div><em className={category.published ? "published" : "draft"}>{category.published ? "已发布" : "草稿"}</em></div>)}</div><form className="cms-card cms-form" onSubmit={add}><h2>添加分类</h2><label>英文名称<input required name="name" placeholder="例如：Ceiling Lights" /></label><label>中文名称<input name="nameZh" placeholder="例如：吸顶灯" /></label><label>URL 别名<input required name="slug" placeholder="ceiling-lights" /></label><label>简短描述<textarea required name="description" /></label><button className="cms-gold">创建分类</button></form></div>; }
function Inquiries({ inquiries, update }: { inquiries: Inquiry[]; update: (inquiry: Inquiry, status: string) => Promise<void> }) { return <div className="cms-card"><div className="card-title"><h2>买家询盘管理</h2><small>{inquiries.length} 条会话</small></div><div className="inquiry-list">{inquiries.map((inquiry) => <article key={inquiry.id}><div className="cms-avatar">{inquiry.name[0]}</div><div><b>{inquiry.name} <small>· {inquiry.company || "个人买家"}</small></b><small>{inquiry.email} · {new Date(inquiry.createdAt).toLocaleDateString("zh-CN")}</small><p>{inquiry.message}</p></div><select value={inquiry.status} onChange={(event) => void update(inquiry, event.target.value)}><option value="New">新询盘</option><option value="Contacted">已联系</option><option value="Quoted">已报价</option><option value="Closed">已关闭</option></select></article>)}</div></div>; }
function Media({ products }: { products: Product[] }) { return <div className="cms-card"><div className="card-title"><h2>媒体库</h2><a className="cms-gold" href="/admin/media">上传媒体</a></div><p className="cms-help">打开安全的本地媒体管理器上传原图，再将图片地址复制到产品编辑器。</p><div className="media-grid">{products.map((product) => <article key={product.id}><img src={product.image} alt="" /><small>{product.model}</small><b>{product.name}</b></article>)}</div></div>; }
function Seo({ settings, setSettings, save }: { settings: SiteSettings; setSettings: (settings: SiteSettings) => void; save: (event: FormEvent) => Promise<void> }) { return <form className="cms-card cms-form seo" onSubmit={save}><div className="card-title"><h2>首页 SEO</h2><small>英文主语言</small></div><label>SEO 标题<input value={settings.seoTitle || ""} onChange={(event) => setSettings({ ...settings, seoTitle: event.target.value })} /></label><label>Meta 描述<textarea value={settings.seoDescription || ""} onChange={(event) => setSettings({ ...settings, seoDescription: event.target.value })} /></label><label>中文 SEO 标题<input value={settings.seoTitleZh || ""} onChange={(event) => setSettings({ ...settings, seoTitleZh: event.target.value })} /></label><label>中文 Meta 描述<textarea value={settings.seoDescriptionZh || ""} onChange={(event) => setSettings({ ...settings, seoDescriptionZh: event.target.value })} /></label><button className="cms-gold">保存 SEO 内容</button></form>; }
function SettingsPanel({ settings, setSettings, save }: { settings: SiteSettings; setSettings: (settings: SiteSettings) => void; save: (event: FormEvent) => Promise<void> }) { return <form className="cms-two" onSubmit={save}><section className="cms-card cms-form"><h2>公司信息</h2>{[["companyName", "网站名称"], ["companyNameZh", "中文网站名称"], ["email", "询盘邮箱"], ["phone", "联系电话"], ["address", "工厂地址"], ["facebookUrl", "Facebook 链接"], ["whatsappUrl", "WhatsApp 链接"], ["instagramUrl", "Instagram 链接"], ["linkedinUrl", "LinkedIn 链接"]].map(([key, label]) => <label key={key}>{label}<input type={key.endsWith("Url") ? "url" : "text"} placeholder={key.endsWith("Url") ? "https://" : undefined} value={settings[key as keyof SiteSettings] as string || ""} onChange={(event) => setSettings({ ...settings, [key]: event.target.value })} /></label>)}<button className="cms-gold">保存设置</button></section><section className="cms-card"><h2>网站语言</h2><div className="language-status"><div><b>English</b><small>主语言</small></div><em>已启用</em></div><div className="language-status"><div><b>简体中文</b><small>辅助语言</small></div><em>已启用</em></div><p className="cms-help">每个产品编辑器都包含中英文内容字段，页面和 SEO 也可以继续维护双语内容。</p></section></form>; }
