"use client";

import Link from "next/link";
import { useLocale } from "./Locale";

export function AboutContent({ brand }: { brand?: { title: string; content: string } }) {
  const { locale } = useLocale(); const chinese = locale === "zh";
  const facts = chinese ? [["1998", "成立"], ["2,000 m²", "工厂能力"], ["24", "工艺专家"], ["420", "年度项目简报"]] : [["1998", "Founded"], ["2,000 m²", "Factory capability"], ["24", "Craft specialists"], ["420", "Annual project briefs"]];
  const support = chinese ? [["01", "快速且务实的报价"], ["02", "目标市场电气方案"], ["03", "定制产品包装"], ["04", "销售与营销资料"]] : [["01", "Fast, practical quotations"], ["02", "Target-market electrical options"], ["03", "Custom product packaging"], ["04", "Sales and marketing materials"]];
  return <><section className="about-hero"><div><span className="eyebrow">{chinese ? "装饰灯具制造商 · 中国中山" : "DECORATIVE LIGHTING MANUFACTURER · ZHONGSHAN, CHINA"}</span><h1>{chinese ? <>为真实空间<br /><i>而造的灯光。</i></> : <>Lighting made<br />for <i>real spaces.</i></>}</h1><p>{chinese ? "我们协助批发和项目采购方，将装饰照明概念转化为清晰、可生产的灯具。" : "We help wholesale and project buyers turn a decorative lighting concept into a clear, production-ready fixture."}</p><Link className="gold" href="/products">{chinese ? "浏览产品" : "Explore products"}</Link></div><img loading="lazy" decoding="async" src="/images/lumenhaus-aster-chandelier.webp" alt="Original chandelier product placeholder" /></section><section className="facts">{facts.map(([value, label]) => <div key={value}><b>{value}</b><span>{label}</span></div>)}</section>{brand ? <section className="copy-section"><h2>{brand.title}</h2><p style={{whiteSpace:"pre-wrap"}}>{brand.content}</p></section> : <section className="copy-section"><span className="eyebrow">{chinese ? "企业简介" : "COMPANY PROFILE"}</span><h2>{chinese ? "一家围绕采购细节而建立的工作室。" : "A studio built around the details that buyers can’t afford to miss."}</h2><p>{chinese ? "从早期比例研究到金属加工、组装、检验和包装，每个阶段都服务于同一个目标：帮助采购方在自己的市场中呈现可靠、优雅的灯具。" : "From early proportion studies through metalwork, assembly, inspection and packing, every stage has one purpose: help a buyer present reliable, beautiful lighting in their own market."}</p></section>}<section className="support"><span className="eyebrow">{chinese ? "采购支持" : "BUYER SUPPORT"}</span><h2>{chinese ? "不止于灯具的支持。" : "Support beyond the fixture."}</h2><div>{support.map(([number, title]) => <article key={number}><b>{number}</b><h3>{title}</h3><p>{chinese ? "为批发、定制开发和商业项目提供清晰信息与务实协同。" : "Clear information and practical coordination for wholesale, custom development and commercial projects."}</p></article>)}</div></section></>;
}

