"use client";

import Link from "next/link";
import { useLocale } from "./Locale";

export function CustomLightingContent() {
  const { locale } = useLocale(); const chinese = locale === "zh";
  const steps = chinese ? [["01", "参考与需求", "提供图纸、样品或参考图，并说明数量、尺寸和使用场景。"], ["02", "结构与材料", "确认比例、玻璃、表面工艺、电气细节和可生产的结构。"], ["03", "报价与样品", "评估价格基础、样品路径、包装要求和交期。"], ["04", "生产支持", "协调生产、检验、出口包装和发运信息。"]] : [["01", "Reference & requirements", "Share a drawing, sample or image with quantities, dimensions and target use."], ["02", "Structure & materials", "Confirm scale, glass, finish, electrical details and practical construction."], ["03", "Quotation & sample", "Review the price basis, sample route, packing requirements and lead time."], ["04", "Production support", "Coordinate production, inspection, export packing and shipment information."]];
  const checklist = chinese ? ["参考图片、图纸或样品", "产品尺寸和材料", "目标数量和目的地市场", "电气、认证和包装要求", "目标生产或交付日期"] : ["Reference image, drawing or sample", "Product dimensions and materials", "Target quantity and destination market", "Electrical, certification and packing needs", "Target production or delivery date"];
  return <><section className="custom-hero"><div><span className="eyebrow">{chinese ? "定制灯具服务" : "CUSTOM LIGHTING SERVICE"}</span><h1>{chinese ? <>从参考图<br />到<i>可生产的灯具。</i></> : <>From reference image<br />to <i>production-ready</i> light.</>}</h1><p>{chinese ? "面向合格批发商和项目采购方的 OEM、ODM 和非标装饰灯具开发。" : "OEM, ODM and non-standard decorative lighting development for qualified wholesale and project buyers."}</p><Link className="gold" href="/contact">{chinese ? "讨论定制项目 ↗" : "Discuss a custom project ↗"}</Link></div><div className="custom-orbs"><i /><i /><i /></div></section><section className="custom-steps"><span className="eyebrow">{chinese ? "实用的开发路径" : "A PRACTICAL DEVELOPMENT PATH"}</span><h2>{chinese ? <>从概念走向<br /><i>可落地的灯具。</i></> : <>Move from concept to a<br />fixture you can specify.</>}</h2><div>{steps.map(([number, title, description]) => <article key={number}><b>{number}</b><h3>{title}</h3><p>{description}</p></article>)}</div></section><section className="custom-checklist"><div><span className="eyebrow">{chinese ? "从需求开始" : "START WITH YOUR REQUIREMENT"}</span><h2>{chinese ? <>为了更好的报价<br /><i>请准备这些。</i></> : <>What to send<br />for a better quote.</>}</h2></div><ul>{checklist.map((item) => <li key={item}>{item}</li>)}</ul><Link className="gold" href="/contact">{chinese ? "发送项目详情 ↗" : "Send project details ↗"}</Link></section></>;
}
