"use client";

import Link from "next/link";
import { ProductGallery } from "./ProductGallery";
import { AddToQuote } from "./QuoteList";
import { categoryZh, useLocale } from "./Locale";

type Product = { id: string; name: string; model: string; category: string; price: string; description: string; image: string };
export function ProductDetail({ product, related }: { product: Product; related: Product[] }) {
  const { locale } = useLocale(); const chinese = locale === "zh"; const category = chinese ? categoryZh[product.category] || product.category : product.category;
  const specs = chinese ? [["产品类型", category], ["型号系列", product.model], ["材质", "喷粉金属 + 装饰玻璃"], ["表面处理", "石墨黑 / 暖黄铜可选"], ["光源", "可按项目规格确认"], ["安装方式", "按型号为吊装或壁装"], ["包装", "出口纸箱及保护内衬"]] : [["Product type", product.category], ["Model series", product.model], ["Material", "Powder-coated metal + decorative glass"], ["Finish", "Graphite black / warm brass options"], ["Light source", "Project specification on request"], ["Installation", "Ceiling or wall mounted according to model"], ["Packing", "Export carton with protective inserts"]];
  return <main className="product-page"><div className="crumb"><Link href="/products">{chinese ? "全部产品" : "All products"}</Link> / <Link href={`/products#${product.category.replaceAll(" ", "-")}`}>{category}</Link> / {product.model}</div><section className="product-intro"><ProductGallery image={product.image} name={product.name} /><article><span className="eyebrow">{chinese ? "B2B 批发 / 项目供应" : "B2B WHOLESALE / PROJECT SUPPLY"}</span><h1>{product.name}</h1><p>{product.description}</p><dl><div><dt>{chinese ? "系列" : "Series"}</dt><dd>{product.model}</dd></div><div><dt>{chinese ? "批发参考" : "Wholesale guide"}</dt><dd>{product.price}</dd></div><div><dt>{chinese ? "分类" : "Category"}</dt><dd>{category}</dd></div></dl><div className="product-actions"><Link className="gold" href={`/contact?model=${product.model}`}>{chinese ? "获取批发报价 ↗" : "Request wholesale quote ↗"}</Link><AddToQuote item={{ id: product.id, name: product.name, model: product.model, image: product.image }} /></div></article></section><section className="spec-section"><div><span className="eyebrow">{chinese ? "产品参数" : "PRODUCT SPECIFICATIONS"}</span><h2>{chinese ? <>项目团队需要的<br /><i>关键信息。</i></> : <>Information your<br /><i>project team needs.</i></>}</h2><p>{chinese ? "参数用于采购演示；最终尺寸、电气要求、表面工艺与包装均会在报价阶段确认。" : "Specifications are shown as a buyer-friendly demonstration. Final dimensions, electrical requirements, finishes and packing are confirmed during quotation."}</p></div><div className="spec-table">{specs.map(([term, value]) => <div key={term}><b>{term}</b><span>{value}</span></div>)}</div></section><section className="models"><span className="eyebrow">{chinese ? "可选型号配置" : "AVAILABLE MODEL OPTIONS"}</span><h2>{chinese ? "配置系列产品。" : "Configure the collection."}</h2>{[3, 5, 8].map((lights) => <div key={lights}><b>{product.model}-{lights}</b><span>{chinese ? `${lights} 头灯配置` : `${lights} light configuration`}</span><span>{chinese ? "支持定制尺寸" : "Custom dimensions available"}</span><Link href={`/contact?model=${product.model}-${lights}`}>{chinese ? "索取详情 ↗" : "Request details ↗"}</Link></div>)}</section><section className="related"><div className="section-heading"><span className="eyebrow">{chinese ? "同系列推荐" : "MORE FROM THE COLLECTION"}</span><h2>{chinese ? "相关产品" : "Related pieces"}</h2></div><div className="archive-grid">{related.map((item) => <Link className="archive-card" key={item.id} href={`/product/${item.id}`}><div><img src={item.image} alt={item.name} /></div><small>{item.model}</small><h3>{item.name}</h3></Link>)}</div></section></main>;
}
