"use client";

import { FormEvent, useEffect, useState } from "react";

type Category = { id: string; name: string; nameZh?: string; slug: string; description: string; published: boolean };
const blank: Omit<Category, "id"> = { name: "", nameZh: "", slug: "", description: "", published: true };

export default function CategoryManager() {
  const [categories, setCategories] = useState<Category[]>([]); const [editing, setEditing] = useState<Partial<Category> | null>(null); const [notice, setNotice] = useState("");
  const load = async () => setCategories(await fetch("/api/categories").then((response) => response.json()));
  useEffect(() => { void load(); }, []);
  async function save(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/categories", { method: editing?.id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing) }); if (response.ok) { setNotice("Category saved."); setEditing(null); await load(); } else setNotice("Unable to save category."); }
  return <main className="product-manager"><header><a className="brand" href="/admin"><i /> LUMENHAUS<small>CMS WORKSPACE</small></a><a href="/admin">← Dashboard</a></header><section><div className="manager-heading"><div><span className="eyebrow">CATALOGUE STRUCTURE</span><h1>Category editor</h1><p>Maintain the public category labels used by the catalogue and product editor.</p></div><button className="cms-gold" onClick={() => setEditing(blank)}>+ New category</button></div><div className="manager-grid"><div className="manager-list"><div className="manager-filter"><b>{categories.length} categories</b><span>Click a category to edit</span></div>{categories.map((category) => <button className={editing?.id === category.id ? "selected" : ""} key={category.id} onClick={() => setEditing(category)}><span className="article-initial">▤</span><span><b>{category.name}</b><small>/{category.slug} · {category.nameZh || "No Chinese label"}</small></span><em className={category.published ? "published" : "draft"}>{category.published ? "Published" : "Draft"}</em></button>)}</div>{editing ? <form className="manager-form" onSubmit={save}><div className="manager-form-title"><h2>{editing.id ? "Edit category" : "New category"}</h2><button type="button" onClick={() => setEditing(null)}>×</button></div><label>English name<input required value={editing.name || ""} onChange={(event) => setEditing({ ...editing, name: event.target.value })} /></label><label>中文名称<input value={editing.nameZh || ""} onChange={(event) => setEditing({ ...editing, nameZh: event.target.value })} /></label><label>URL slug<input required value={editing.slug || ""} onChange={(event) => setEditing({ ...editing, slug: event.target.value })} /></label><label>Short description<textarea required value={editing.description || ""} onChange={(event) => setEditing({ ...editing, description: event.target.value })} /></label><label className="featured"><input type="checkbox" checked={editing.published !== false} onChange={(event) => setEditing({ ...editing, published: event.target.checked })} /> Publish in catalogue controls</label><div className="form-actions"><button className="cms-gold">Save category</button></div></form> : <div className="manager-empty"><b>▤</b><h2>Select a category</h2><p>Choose an existing category or create a new catalogue group.</p></div>}</div></section>{notice && <div className="toast">{notice}<button onClick={() => setNotice("")}>×</button></div>}</main>;
}
