"use client";

import { FormEvent, useEffect, useState } from "react";

type Category = { id: string; name: string; nameZh?: string; slug: string; description: string; published: boolean };
const blank: Omit<Category, "id"> = { name: "", nameZh: "", slug: "", description: "", published: true };

export default function CategoryManager() {
  const [categories, setCategories] = useState<Category[]>([]); const [editing, setEditing] = useState<Partial<Category> | null>(null); const [notice, setNotice] = useState("");
  const load = async () => setCategories(await fetch("/api/categories").then((response) => response.json()));
  useEffect(() => { void load(); }, []);
  async function save(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/categories", { method: editing?.id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing) }); if (response.ok) { setNotice("分类已保存。"); setEditing(null); await load(); } else setNotice("分类保存失败，请重试。"); }
  return <main className="product-manager"><header><a className="brand" href="/admin"><i /> LUMENHAUS<small>后台工作台</small></a><a href="/admin">← 返回后台</a></header><section><div className="manager-heading"><div><span className="eyebrow">目录结构</span><h1>分类编辑</h1><p>维护产品目录和产品编辑器使用的公开分类标签。</p></div><button className="cms-gold" onClick={() => setEditing(blank)}>+ 新建分类</button></div><div className="manager-grid"><div className="manager-list"><div className="manager-filter"><b>{categories.length} 个分类</b><span>点击分类进行编辑</span></div>{categories.map((category) => <button className={editing?.id === category.id ? "selected" : ""} key={category.id} onClick={() => setEditing(category)}><span className="article-initial">▤</span><span><b>{category.name}</b><small>/{category.slug} · {category.nameZh || "暂无中文名称"}</small></span><em className={category.published ? "published" : "draft"}>{category.published ? "已发布" : "草稿"}</em></button>)}</div>{editing ? <form className="manager-form" onSubmit={save}><div className="manager-form-title"><h2>{editing.id ? "编辑分类" : "新建分类"}</h2><button type="button" onClick={() => setEditing(null)}>×</button></div><label>英文名称<input required value={editing.name || ""} onChange={(event) => setEditing({ ...editing, name: event.target.value })} /></label><label>中文名称<input value={editing.nameZh || ""} onChange={(event) => setEditing({ ...editing, nameZh: event.target.value })} /></label><label>URL 别名<input required value={editing.slug || ""} onChange={(event) => setEditing({ ...editing, slug: event.target.value })} /></label><label>简短描述<textarea required value={editing.description || ""} onChange={(event) => setEditing({ ...editing, description: event.target.value })} /></label><label className="featured"><input type="checkbox" checked={editing.published !== false} onChange={(event) => setEditing({ ...editing, published: event.target.checked })} /> 在目录中启用</label><div className="form-actions"><button className="cms-gold">保存分类</button></div></form> : <div className="manager-empty"><b>▤</b><h2>选择一个分类</h2><p>选择已有分类或创建新的目录分组。</p></div>}</div></section>{notice && <div className="toast">{notice}<button onClick={() => setNotice("")}>×</button></div>}</main>;
}
